# Generated by Django 5.2.5 on 2025-08-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Order_App', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/store/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Order_App.category')),
                ('products', models.ManyToManyField(blank=True, related_name='stores', to='Food_Order_App.product')),
            ],
        ),
    ]
