# Generated by Django 5.2.5 on 2025-08-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Order_App', '0005_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, related_name='stores', to='Food_Order_App.product'),
        ),
    ]
